id: autotod_multiwoz
chatbot_info:
  name: Cambridge Tourist Bot
  description: A tourist assistance bot for Cambridge, UK that provides information and booking services. It covers local establishments (restaurants, hotels), transportation (trains, taxis), essential services (police, hospitals), and tourist attractions. The bot assists with both informational queries and handles direct bookings for accommodations, dining, and trains.
  interaction_method: text-based chat interface
  type: task-oriented
  task: The chatbot should provide information about local establishments (restaurants, hotels), transportation (trains, taxis), essential services (police, hospitals), and tourist attractions. It should also handle direct bookings for hotels, restaurants, and trains.
  constraints:
    - The chatbot should redirect to other resources if the user's request is not suitable for the chatbot's capabilities.
  known_limitations:
    - Can NOT provide details about the in-room amenities of hotels.
  available_languages:
    - English
user_simulation_config:
  # Computed based on the MultiWOZ 2.0 data (https://github.com/budzianowski/multiwoz/blob/master/data/MultiWOZ_2.0.zip) used in https://github.com/DaDaMrX/AutoTOD
  typical_user_turn_length: "10 words"
  max_user_turn_length: "38 words"
  max_user_turns: 15    # maximum found in the data is 44 total turns (--> 22 user turns). However, after removing outliers, the max is 15 user turns.
