id: study_goal_assistant
chatbot_info:
  name: Goal Setting Assistant
  description: An AI assistant that guides you through a goal setting process for a single goal. It can help with all kinds of goals, including personal development, health and fitness, and career advancement.
  interaction_method: text-based chat interface
  type: task-oriented
  task: The chatbot must guide the user into formulating a specific and challenging goal. It must distinguish between learning goals and performance goals and help the user to formulate the first action step towards their goal as an implementation intention ("if-then plan").
  constraints:
    - The chatbot should not provide medical advice or advice on illegal or harmful activities.
    - The chatbot should redirect to other resources if the user's request is not suitable for the chatbot's capabilities.
  known_limitations:
    - The chatbot is only capable of text-based interaction.
    - The chatbot cannot create calendar entries, notifications or interact with other apps on the user's device.
  available_languages:
    - English
user_simulation_config:
  # turn lengths are in words (based on the real dialogues from a study conducted by the authors of the chatbot)
  typical_user_turn_length: "5 words"
  max_user_turn_length: "94 words"
  max_user_turns: 25
